package com.example.android_db_biz.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.android_db_biz.vo.Singer;
import com.example.android_db_biz.vo.MenuInfo;
import com.example.android_db_biz.vo.Song;

import com.example.android_db_biz.greendao.SingerDao;
import com.example.android_db_biz.greendao.MenuInfoDao;
import com.example.android_db_biz.greendao.SongDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig singerDaoConfig;
    private final DaoConfig menuInfoDaoConfig;
    private final DaoConfig songDaoConfig;

    private final SingerDao singerDao;
    private final MenuInfoDao menuInfoDao;
    private final SongDao songDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        singerDaoConfig = daoConfigMap.get(SingerDao.class).clone();
        singerDaoConfig.initIdentityScope(type);

        menuInfoDaoConfig = daoConfigMap.get(MenuInfoDao.class).clone();
        menuInfoDaoConfig.initIdentityScope(type);

        songDaoConfig = daoConfigMap.get(SongDao.class).clone();
        songDaoConfig.initIdentityScope(type);

        singerDao = new SingerDao(singerDaoConfig, this);
        menuInfoDao = new MenuInfoDao(menuInfoDaoConfig, this);
        songDao = new SongDao(songDaoConfig, this);

        registerDao(Singer.class, singerDao);
        registerDao(MenuInfo.class, menuInfoDao);
        registerDao(Song.class, songDao);
    }
    
    public void clear() {
        singerDaoConfig.clearIdentityScope();
        menuInfoDaoConfig.clearIdentityScope();
        songDaoConfig.clearIdentityScope();
    }

    public SingerDao getSingerDao() {
        return singerDao;
    }

    public MenuInfoDao getMenuInfoDao() {
        return menuInfoDao;
    }

    public SongDao getSongDao() {
        return songDao;
    }

}
