package com.example.android_db_biz.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.android_db_biz.vo.Singer;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SINGER".
*/
public class SingerDao extends AbstractDao<Singer, Long> {

    public static final String TABLENAME = "SINGER";

    /**
     * Properties of entity Singer.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property SingerCode = new Property(1, String.class, "singerCode", false, "SINGER_CODE");
        public final static Property SingerName = new Property(2, String.class, "singerName", false, "SINGER_NAME");
        public final static Property SingerDesc = new Property(3, String.class, "singerDesc", false, "SINGER_DESC");
    }


    public SingerDao(DaoConfig config) {
        super(config);
    }
    
    public SingerDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SINGER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"SINGER_CODE\" TEXT," + // 1: singerCode
                "\"SINGER_NAME\" TEXT," + // 2: singerName
                "\"SINGER_DESC\" TEXT);"); // 3: singerDesc
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SINGER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Singer entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String singerCode = entity.getSingerCode();
        if (singerCode != null) {
            stmt.bindString(2, singerCode);
        }
 
        String singerName = entity.getSingerName();
        if (singerName != null) {
            stmt.bindString(3, singerName);
        }
 
        String singerDesc = entity.getSingerDesc();
        if (singerDesc != null) {
            stmt.bindString(4, singerDesc);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Singer entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String singerCode = entity.getSingerCode();
        if (singerCode != null) {
            stmt.bindString(2, singerCode);
        }
 
        String singerName = entity.getSingerName();
        if (singerName != null) {
            stmt.bindString(3, singerName);
        }
 
        String singerDesc = entity.getSingerDesc();
        if (singerDesc != null) {
            stmt.bindString(4, singerDesc);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Singer readEntity(Cursor cursor, int offset) {
        Singer entity = new Singer( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // singerCode
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // singerName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // singerDesc
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Singer entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSingerCode(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setSingerName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSingerDesc(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Singer entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Singer entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Singer entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
